services:
  - type: web
    name: moj-sktorentonline-stremio
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADDON_ID
        value: com.skuskazariadeni.onlinesktorrent.stremio
      - key: ADDON_NAME
        value: SKTonline Online Streams
      - key: ADDON_VERSION
        value: 1.0.0
      - key: CATALOG_ID
        value: online_sktorrent_catalog
      - key: CATALOG_NAME
        value: SKTonline Online Streams
